export const CATEGORIES = {
  estate_cleanout: {
    label: 'Estate Cleanout',
    slug: 'estate-cleanout',
    description: 'Professional estate cleanout services for homes, offices, and properties',
  },
  junk_removal: {
    label: 'Junk Removal',
    slug: 'junk-removal',
    description: 'Fast and reliable junk removal for residential and commercial properties',
  },
} as const;

export const US_STATES = [
  { abbr: 'AL', name: 'Alabama' },
  { abbr: 'AK', name: 'Alaska' },
  { abbr: 'AZ', name: 'Arizona' },
  { abbr: 'AR', name: 'Arkansas' },
  { abbr: 'CA', name: 'California' },
  { abbr: 'CO', name: 'Colorado' },
  { abbr: 'CT', name: 'Connecticut' },
  { abbr: 'DE', name: 'Delaware' },
  { abbr: 'FL', name: 'Florida' },
  { abbr: 'GA', name: 'Georgia' },
  { abbr: 'HI', name: 'Hawaii' },
  { abbr: 'ID', name: 'Idaho' },
  { abbr: 'IL', name: 'Illinois' },
  { abbr: 'IN', name: 'Indiana' },
  { abbr: 'IA', name: 'Iowa' },
  { abbr: 'KS', name: 'Kansas' },
  { abbr: 'KY', name: 'Kentucky' },
  { abbr: 'LA', name: 'Louisiana' },
  { abbr: 'ME', name: 'Maine' },
  { abbr: 'MD', name: 'Maryland' },
  { abbr: 'MA', name: 'Massachusetts' },
  { abbr: 'MI', name: 'Michigan' },
  { abbr: 'MN', name: 'Minnesota' },
  { abbr: 'MS', name: 'Mississippi' },
  { abbr: 'MO', name: 'Missouri' },
  { abbr: 'MT', name: 'Montana' },
  { abbr: 'NE', name: 'Nebraska' },
  { abbr: 'NV', name: 'Nevada' },
  { abbr: 'NH', name: 'New Hampshire' },
  { abbr: 'NJ', name: 'New Jersey' },
  { abbr: 'NM', name: 'New Mexico' },
  { abbr: 'NY', name: 'New York' },
  { abbr: 'NC', name: 'North Carolina' },
  { abbr: 'ND', name: 'North Dakota' },
  { abbr: 'OH', name: 'Ohio' },
  { abbr: 'OK', name: 'Oklahoma' },
  { abbr: 'OR', name: 'Oregon' },
  { abbr: 'PA', name: 'Pennsylvania' },
  { abbr: 'RI', name: 'Rhode Island' },
  { abbr: 'SC', name: 'South Carolina' },
  { abbr: 'SD', name: 'South Dakota' },
  { abbr: 'TN', name: 'Tennessee' },
  { abbr: 'TX', name: 'Texas' },
  { abbr: 'UT', name: 'Utah' },
  { abbr: 'VT', name: 'Vermont' },
  { abbr: 'VA', name: 'Virginia' },
  { abbr: 'WA', name: 'Washington' },
  { abbr: 'WV', name: 'West Virginia' },
  { abbr: 'WI', name: 'Wisconsin' },
  { abbr: 'WY', name: 'Wyoming' },
] as const;

export const SORT_OPTIONS = [
  { value: 'rating', label: 'Highest Rated' },
  { value: 'name', label: 'Name (A–Z)' },
  { value: 'newest', label: 'Newest' },
] as const;

export const PAGE_SIZE = 12;

export const CITIES_BY_STATE: Record<string, string[]> = {
  AK: ['Anchorage', 'Fairbanks', 'Juneau', 'Wasilla'],
  AL: ['Birmingham', 'Huntsville', 'Mobile', 'Montgomery'],
  AR: ['Fayetteville', 'Fort Smith', 'Little Rock', 'Springdale'],
  AZ: ['Chandler', 'Mesa', 'Phoenix', 'Scottsdale', 'Tempe', 'Tucson'],
  CA: ['Anaheim', 'Bakersfield', 'Fresno', 'Long Beach', 'Los Angeles', 'Oakland', 'Sacramento', 'San Diego', 'San Francisco', 'San Jose'],
  CO: ['Aurora', 'Colorado Springs', 'Denver', 'Fort Collins', 'Lakewood', 'Thornton'],
  CT: ['Bridgeport', 'Hartford', 'New Haven', 'Stamford'],
  DE: ['Dover', 'Middletown', 'Newark', 'Wilmington'],
  FL: ['Cape Coral', 'Fort Lauderdale', 'Hialeah', 'Jacksonville', 'Miami', 'Orlando', 'Port St. Lucie', 'St. Petersburg', 'Tallahassee', 'Tampa'],
  GA: ['Athens', 'Atlanta', 'Augusta', 'Columbus', 'Macon', 'Savannah'],
  HI: ['Hilo', 'Honolulu', 'Kailua', 'Pearl City'],
  IA: ['Cedar Rapids', 'Davenport', 'Des Moines', 'Sioux City'],
  ID: ['Boise', 'Idaho Falls', 'Meridian', 'Nampa'],
  IL: ['Aurora', 'Chicago', 'Joliet', 'Peoria', 'Rockford', 'Springfield'],
  IN: ['Carmel', 'Evansville', 'Fishers', 'Fort Wayne', 'Indianapolis', 'South Bend'],
  KS: ['Kansas City', 'Overland Park', 'Topeka', 'Wichita'],
  KY: ['Bowling Green', 'Lexington', 'Louisville', 'Owensboro'],
  LA: ['Baton Rouge', 'Lafayette', 'New Orleans', 'Shreveport'],
  MA: ['Boston', 'Cambridge', 'Lowell', 'New Bedford', 'Springfield', 'Worcester'],
  MD: ['Baltimore', 'Bowie', 'Frederick', 'Gaithersburg', 'Hagerstown', 'Rockville'],
  ME: ['Bangor', 'Lewiston', 'Portland', 'South Portland'],
  MI: ['Ann Arbor', 'Detroit', 'Grand Rapids', 'Lansing', 'Sterling Heights', 'Warren'],
  MN: ['Bloomington', 'Brooklyn Park', 'Duluth', 'Minneapolis', 'Rochester', 'St. Paul'],
  MO: ['Columbia', "Lee's Summit", 'Independence', 'Kansas City', 'Springfield', 'St. Louis'],
  MS: ['Gulfport', 'Hattiesburg', 'Jackson', 'Southaven'],
  MT: ['Billings', 'Bozeman', 'Great Falls', 'Missoula'],
  NC: ['Charlotte', 'Durham', 'Fayetteville', 'Greensboro', 'Raleigh', 'Winston-Salem'],
  ND: ['Bismarck', 'Fargo', 'Grand Forks', 'Minot'],
  NE: ['Bellevue', 'Grand Island', 'Lincoln', 'Omaha'],
  NH: ['Concord', 'Derry', 'Manchester', 'Nashua'],
  NJ: ['Camden', 'Elizabeth', 'Jersey City', 'Newark', 'Paterson', 'Trenton'],
  NM: ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe'],
  NV: ['Henderson', 'Las Vegas', 'North Las Vegas', 'Reno'],
  NY: ['Albany', 'Buffalo', 'Mount Vernon', 'New Rochelle', 'New York City', 'Rochester', 'Schenectady', 'Syracuse', 'Utica', 'Yonkers'],
  OH: ['Akron', 'Cincinnati', 'Cleveland', 'Columbus', 'Dayton', 'Toledo'],
  OK: ['Broken Arrow', 'Norman', 'Oklahoma City', 'Tulsa'],
  OR: ['Eugene', 'Gresham', 'Portland', 'Salem'],
  PA: ['Allentown', 'Erie', 'Philadelphia', 'Pittsburgh', 'Reading', 'Scranton'],
  RI: ['Cranston', 'Pawtucket', 'Providence', 'Warwick'],
  SC: ['Charleston', 'Columbia', 'Greenville', 'North Charleston'],
  SD: ['Aberdeen', 'Brookings', 'Rapid City', 'Sioux Falls'],
  TN: ['Chattanooga', 'Clarksville', 'Knoxville', 'Memphis', 'Murfreesboro', 'Nashville'],
  TX: ['Arlington', 'Austin', 'Corpus Christi', 'Dallas', 'El Paso', 'Fort Worth', 'Houston', 'Lubbock', 'Plano', 'San Antonio'],
  UT: ['Provo', 'Salt Lake City', 'West Jordan', 'West Valley City'],
  VA: ['Arlington', 'Chesapeake', 'Newport News', 'Norfolk', 'Richmond', 'Virginia Beach'],
  VT: ['Barre', 'Burlington', 'Rutland', 'South Burlington'],
  WA: ['Bellevue', 'Kirkland', 'Seattle', 'Spokane', 'Tacoma', 'Vancouver'],
  WI: ['Appleton', 'Green Bay', 'Kenosha', 'Madison', 'Milwaukee', 'Racine'],
  WV: ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg'],
  WY: ['Casper', 'Cheyenne', 'Gillette', 'Laramie'],
};
