import type { Category } from '@/types'

interface SeedBusiness {
  name: string
  slug: string
  category: Category
  description: string
  phone: string
  email: string
  website?: string
  street_address: string
  city: string
  state: string
  state_full: string
  zip_code: string
  years_in_business: number
  insured: boolean
  bonded: boolean
  featured: boolean
  images: { url: string; alt_text: string; is_primary: boolean; sort_order: number }[]
}

interface SeedReview {
  business_slug: string
  reviewer_name: string
  rating: number
  title: string
  body: string
}

// Curated Unsplash photo IDs for junk removal / estate cleanout
const PHOTOS = {
  junk: [
    { id: '1558618666-fcd25c85cd64', alt: 'Junk removal truck loaded with debris' },
    { id: '1558618666-fcd25c85cd64', alt: 'Crew removing furniture from home' },
    { id: '1504307651254-35680f356dfd', alt: 'Dumpster bin for waste removal' },
    { id: '1581578731548-c64695cc6952', alt: 'Team clearing out garage clutter' },
    { id: '1530124566582-a618bc2615dc', alt: 'Junk removal professionals at work' },
    { id: '1517142089942-ba376ce32a2e', alt: 'Clean up crew hauling away trash' },
    { id: '1558618047-3c8c76ca7d13', alt: 'Residential junk removal service' },
    { id: '1584622650111-993a426fbf0a', alt: 'Large item pickup service' },
  ],
  estate: [
    { id: '1484154218962-a197022b6ac6', alt: 'Estate cleanout team at work' },
    { id: '1558997519-4d2054aee6c4', alt: 'Professional estate cleanout service' },
    { id: '1502672260266-1c1ef2d93688', alt: 'House clearance and cleanout' },
    { id: '1512917774080-9991f1c4c750', alt: 'Estate property being cleared out' },
    { id: '1513694203232-719a99b29e6e', alt: 'Professional cleanout crew inside home' },
    { id: '1560448204-603b3fc33ddc', alt: 'Estate items being sorted and removed' },
    { id: '1493809842364-78817add7ffb', alt: 'Property cleanout and hauling service' },
    { id: '1505693416388-ac5ce068fe85', alt: 'Estate clearance in progress' },
  ],
}

function junkPhotos(start = 0, count = 3) {
  return PHOTOS.junk.slice(start % PHOTOS.junk.length, (start % PHOTOS.junk.length) + count).map(
    (p, i) => ({
      url: `https://images.unsplash.com/photo-${p.id}?w=800&q=80`,
      alt_text: p.alt,
      is_primary: i === 0,
      sort_order: i,
    })
  )
}

function estatePhotos(start = 0, count = 3) {
  return PHOTOS.estate.slice(start % PHOTOS.estate.length, (start % PHOTOS.estate.length) + count).map(
    (p, i) => ({
      url: `https://images.unsplash.com/photo-${p.id}?w=800&q=80`,
      alt_text: p.alt,
      is_primary: i === 0,
      sort_order: i,
    })
  )
}

export const SEED_BUSINESSES: SeedBusiness[] = [
  // ── Texas (Austin, Houston, Dallas) ──────────────────────
  {
    name: 'Lone Star Junk Austin',
    slug: 'lone-star-junk-austin-tx',
    category: 'junk_removal',
    description: 'Austin\'s top-rated junk removal service. We haul away furniture, appliances, yard waste, and more. Same-day service available.',
    phone: '5124557890',
    email: 'info@lonestarjunk.com',
    website: 'https://lonestarjunk.com',
    street_address: '1200 S Congress Ave',
    city: 'Austin',
    state: 'TX',
    state_full: 'Texas',
    zip_code: '78704',
    years_in_business: 8,
    insured: true,
    bonded: true,
    featured: true,
    images: junkPhotos(0, 4),
  },
  {
    name: 'Capital City Estate Cleanouts',
    slug: 'capital-city-estate-cleanouts-austin-tx',
    category: 'estate_cleanout',
    description: 'Compassionate and thorough estate cleanout services in Austin and surrounding areas. We handle everything from start to finish.',
    phone: '5123349900',
    email: 'hello@capitalcityestate.com',
    street_address: '3400 N Lamar Blvd',
    city: 'Austin',
    state: 'TX',
    state_full: 'Texas',
    zip_code: '78705',
    years_in_business: 12,
    insured: true,
    bonded: true,
    featured: true,
    images: estatePhotos(0, 4),
  },
  {
    name: 'H-Town Haul Away',
    slug: 'h-town-haul-away-houston-tx',
    category: 'junk_removal',
    description: 'Houston\'s fastest junk removal crew. We\'ll clear out your home, office, or construction site in no time.',
    phone: '7139087654',
    email: 'contact@htownhaul.com',
    street_address: '5600 Westheimer Rd',
    city: 'Houston',
    state: 'TX',
    state_full: 'Texas',
    zip_code: '77056',
    years_in_business: 5,
    insured: true,
    bonded: false,
    featured: false,
    images: junkPhotos(2, 3),
  },
  {
    name: 'Houston Estate Clearance Pro',
    slug: 'houston-estate-clearance-pro-tx',
    category: 'estate_cleanout',
    description: 'Professional estate cleanout services for Houston families. Respectful, efficient, and thorough.',
    phone: '7135671234',
    email: 'support@houstonestates.com',
    street_address: '2100 Main St',
    city: 'Houston',
    state: 'TX',
    state_full: 'Texas',
    zip_code: '77002',
    years_in_business: 9,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(2, 3),
  },
  {
    name: 'DFW Junk Masters',
    slug: 'dfw-junk-masters-dallas-tx',
    category: 'junk_removal',
    description: 'Serving Dallas-Fort Worth with top-notch junk removal. Residential, commercial, and construction debris removal.',
    phone: '2146789012',
    email: 'info@dfwjunkmasters.com',
    street_address: '1800 Commerce St',
    city: 'Dallas',
    state: 'TX',
    state_full: 'Texas',
    zip_code: '75201',
    years_in_business: 6,
    insured: true,
    bonded: true,
    featured: true,
    images: junkPhotos(4, 3),
  },
  {
    name: 'Texas Estates Cleanout',
    slug: 'texas-estates-cleanout-dallas-tx',
    category: 'estate_cleanout',
    description: 'Comprehensive estate cleanout services across Dallas. We donate, recycle, and responsibly dispose of all items.',
    phone: '2147893456',
    email: 'dallas@texasestates.com',
    street_address: '420 Mockingbird Ln',
    city: 'Dallas',
    state: 'TX',
    state_full: 'Texas',
    zip_code: '75205',
    years_in_business: 15,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(4, 3),
  },

  // ── California (Los Angeles, San Francisco, San Diego) ──
  {
    name: 'LA Junk Busters',
    slug: 'la-junk-busters-los-angeles-ca',
    category: 'junk_removal',
    description: 'Los Angeles\' premier junk removal service. We pick up anything from a single item to a full home cleanout.',
    phone: '3235671234',
    email: 'info@lajunkbusters.com',
    street_address: '8500 Wilshire Blvd',
    city: 'Los Angeles',
    state: 'CA',
    state_full: 'California',
    zip_code: '90211',
    years_in_business: 10,
    insured: true,
    bonded: true,
    featured: true,
    images: junkPhotos(1, 4),
  },
  {
    name: 'Hollywood Estate Solutions',
    slug: 'hollywood-estate-solutions-ca',
    category: 'estate_cleanout',
    description: 'Expert estate cleanout services for the Greater Los Angeles area. Discreet, professional, and reliable.',
    phone: '3109876543',
    email: 'la@hollywoodestates.com',
    street_address: '1234 Sunset Blvd',
    city: 'Los Angeles',
    state: 'CA',
    state_full: 'California',
    zip_code: '90026',
    years_in_business: 7,
    insured: true,
    bonded: false,
    featured: false,
    images: estatePhotos(1, 3),
  },
  {
    name: 'Bay Area Junk Away',
    slug: 'bay-area-junk-away-san-francisco-ca',
    category: 'junk_removal',
    description: 'San Francisco\'s eco-conscious junk removal service. We recycle and donate up to 80% of what we collect.',
    phone: '4155671234',
    email: 'sf@bayareajunk.com',
    street_address: '500 Mission St',
    city: 'San Francisco',
    state: 'CA',
    state_full: 'California',
    zip_code: '94105',
    years_in_business: 4,
    insured: true,
    bonded: true,
    featured: false,
    images: junkPhotos(3, 3),
  },
  {
    name: 'Golden Gate Estate Cleaners',
    slug: 'golden-gate-estate-cleaners-sf-ca',
    category: 'estate_cleanout',
    description: 'Full-service estate cleanout for San Francisco Bay Area families. Licensed, bonded, and highly reviewed.',
    phone: '4158901234',
    email: 'info@ggecleaners.com',
    street_address: '200 Van Ness Ave',
    city: 'San Francisco',
    state: 'CA',
    state_full: 'California',
    zip_code: '94102',
    years_in_business: 11,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(3, 3),
  },
  {
    name: 'San Diego Clutter Crushers',
    slug: 'san-diego-clutter-crushers-ca',
    category: 'junk_removal',
    description: 'Fast, affordable junk removal in San Diego. We handle e-waste, mattresses, hot tubs, and more.',
    phone: '6195678901',
    email: 'sd@cluttercrushers.com',
    street_address: '1900 Pacific Hwy',
    city: 'San Diego',
    state: 'CA',
    state_full: 'California',
    zip_code: '92101',
    years_in_business: 3,
    insured: true,
    bonded: false,
    featured: false,
    images: junkPhotos(5, 3),
  },

  // ── Illinois (Chicago) ───────────────────────────────────
  {
    name: 'Windy City Junk Removal',
    slug: 'windy-city-junk-removal-chicago-il',
    category: 'junk_removal',
    description: 'Chicago\'s go-to junk haulers. Fully insured, background-checked crew. We work year-round in all weather.',
    phone: '3125678901',
    email: 'info@windycityjunk.com',
    street_address: '233 N Michigan Ave',
    city: 'Chicago',
    state: 'IL',
    state_full: 'Illinois',
    zip_code: '60601',
    years_in_business: 14,
    insured: true,
    bonded: true,
    featured: true,
    images: junkPhotos(6, 4),
  },
  {
    name: 'Chicago Estate Cleanout Co.',
    slug: 'chicago-estate-cleanout-co-il',
    category: 'estate_cleanout',
    description: 'Trusted estate cleanout specialists serving Chicago and suburbs. We handle hoarder cleanouts, foreclosures, and family estates.',
    phone: '3124567890',
    email: 'chicago@estatecos.com',
    street_address: '1600 W Lake St',
    city: 'Chicago',
    state: 'IL',
    state_full: 'Illinois',
    zip_code: '60612',
    years_in_business: 16,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(5, 4),
  },
  {
    name: 'Loop Junk Haulers',
    slug: 'loop-junk-haulers-chicago-il',
    category: 'junk_removal',
    description: 'Downtown Chicago junk removal specialists. Condo and high-rise friendly — elevator-certified crew.',
    phone: '3129871234',
    email: 'loop@junkdispatch.com',
    street_address: '180 N Wacker Dr',
    city: 'Chicago',
    state: 'IL',
    state_full: 'Illinois',
    zip_code: '60606',
    years_in_business: 5,
    insured: true,
    bonded: false,
    featured: false,
    images: junkPhotos(0, 3),
  },

  // ── New York (NYC, Buffalo) ──────────────────────────────
  {
    name: 'NYC Junk Removal Pros',
    slug: 'nyc-junk-removal-pros-new-york-ny',
    category: 'junk_removal',
    description: 'New York City\'s top-rated junk removal service. We navigate all five boroughs — apartments, brownstones, offices.',
    phone: '2125671234',
    email: 'nyc@junkremovalpros.com',
    street_address: '350 5th Ave',
    city: 'New York',
    state: 'NY',
    state_full: 'New York',
    zip_code: '10118',
    years_in_business: 9,
    insured: true,
    bonded: true,
    featured: false,
    images: junkPhotos(2, 4),
  },
  {
    name: 'Manhattan Estate Clearance',
    slug: 'manhattan-estate-clearance-ny',
    category: 'estate_cleanout',
    description: 'Specialized estate cleanout for Manhattan and the tristate area. White-glove service for high-value estates.',
    phone: '2128907654',
    email: 'info@manhattanec.com',
    website: 'https://manhattanec.com',
    street_address: '125 Park Ave',
    city: 'New York',
    state: 'NY',
    state_full: 'New York',
    zip_code: '10017',
    years_in_business: 20,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(6, 4),
  },
  {
    name: 'Empire State Junk Haulers',
    slug: 'empire-state-junk-haulers-buffalo-ny',
    category: 'junk_removal',
    description: 'Serving Buffalo and Western New York. Affordable, prompt, and professional junk removal.',
    phone: '7164567890',
    email: 'buffalo@empirejunk.com',
    street_address: '500 Main St',
    city: 'Buffalo',
    state: 'NY',
    state_full: 'New York',
    zip_code: '14202',
    years_in_business: 6,
    insured: true,
    bonded: false,
    featured: false,
    images: junkPhotos(4, 3),
  },

  // ── Arizona (Phoenix, Tucson) ────────────────────────────
  {
    name: 'Desert Sun Junk Removal',
    slug: 'desert-sun-junk-removal-phoenix-az',
    category: 'junk_removal',
    description: 'Phoenix\'s most reliable junk removal company. We work 7 days a week to clear your home or business.',
    phone: '6025671234',
    email: 'info@desertsunjunk.com',
    street_address: '2100 N Central Ave',
    city: 'Phoenix',
    state: 'AZ',
    state_full: 'Arizona',
    zip_code: '85004',
    years_in_business: 7,
    insured: true,
    bonded: true,
    featured: false,
    images: junkPhotos(5, 3),
  },
  {
    name: 'Sonoran Estate Cleanouts',
    slug: 'sonoran-estate-cleanouts-phoenix-az',
    category: 'estate_cleanout',
    description: 'Compassionate estate cleanout services in Phoenix. We treat your family\'s belongings with care and respect.',
    phone: '6027893456',
    email: 'phoenix@sonoranec.com',
    street_address: '4000 E Camelback Rd',
    city: 'Phoenix',
    state: 'AZ',
    state_full: 'Arizona',
    zip_code: '85018',
    years_in_business: 8,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(0, 3),
  },
  {
    name: 'Tucson Tough Haulers',
    slug: 'tucson-tough-haulers-az',
    category: 'junk_removal',
    description: 'No job too big or too small for Tucson Tough Haulers. Competitive pricing and same-day availability.',
    phone: '5205671234',
    email: 'info@tucsontough.com',
    street_address: '700 E University Blvd',
    city: 'Tucson',
    state: 'AZ',
    state_full: 'Arizona',
    zip_code: '85719',
    years_in_business: 4,
    insured: true,
    bonded: false,
    featured: false,
    images: junkPhotos(6, 3),
  },

  // ── Georgia (Atlanta) ────────────────────────────────────
  {
    name: 'ATL Junk Removal Squad',
    slug: 'atl-junk-removal-squad-atlanta-ga',
    category: 'junk_removal',
    description: 'Atlanta\'s favorite junk removal squad. Fast pickups, transparent pricing, and a green disposal policy.',
    phone: '4045671234',
    email: 'atl@junkremovalsquad.com',
    street_address: '100 Peachtree St NW',
    city: 'Atlanta',
    state: 'GA',
    state_full: 'Georgia',
    zip_code: '30303',
    years_in_business: 6,
    insured: true,
    bonded: true,
    featured: false,
    images: junkPhotos(1, 3),
  },
  {
    name: 'Peach State Estate Cleaners',
    slug: 'peach-state-estate-cleaners-atlanta-ga',
    category: 'estate_cleanout',
    description: 'Professional estate cleanout across metro Atlanta. We coordinate with realtors, attorneys, and families.',
    phone: '4048901234',
    email: 'info@peachstateestate.com',
    street_address: '750 Ponce De Leon Ave NE',
    city: 'Atlanta',
    state: 'GA',
    state_full: 'Georgia',
    zip_code: '30306',
    years_in_business: 13,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(2, 3),
  },

  // ── Colorado (Denver) ────────────────────────────────────
  {
    name: 'Mile High Junk Removal',
    slug: 'mile-high-junk-removal-denver-co',
    category: 'junk_removal',
    description: 'Denver\'s trusted junk haulers. Eco-friendly disposal with a focus on recycling and donation.',
    phone: '3035671234',
    email: 'denver@milehighjunk.com',
    website: 'https://milehighjunk.com',
    street_address: '1600 Glenarm Pl',
    city: 'Denver',
    state: 'CO',
    state_full: 'Colorado',
    zip_code: '80202',
    years_in_business: 5,
    insured: true,
    bonded: true,
    featured: false,
    images: junkPhotos(3, 3),
  },
  {
    name: 'Rocky Mountain Estate Services',
    slug: 'rocky-mountain-estate-services-denver-co',
    category: 'estate_cleanout',
    description: 'Estate cleanout specialists serving Denver and the Front Range. Sensitive, thorough, and efficient.',
    phone: '3037893456',
    email: 'info@rmestateco.com',
    street_address: '2000 E Colfax Ave',
    city: 'Denver',
    state: 'CO',
    state_full: 'Colorado',
    zip_code: '80206',
    years_in_business: 10,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(4, 3),
  },

  // ── Washington (Seattle) ─────────────────────────────────
  {
    name: 'Emerald City Junk Removal',
    slug: 'emerald-city-junk-removal-seattle-wa',
    category: 'junk_removal',
    description: 'Seattle\'s sustainable junk removal option. We partner with local nonprofits for donation and diversion.',
    phone: '2065671234',
    email: 'seattle@emeraldjunk.com',
    street_address: '400 Broad St',
    city: 'Seattle',
    state: 'WA',
    state_full: 'Washington',
    zip_code: '98109',
    years_in_business: 7,
    insured: true,
    bonded: true,
    featured: false,
    images: junkPhotos(7, 3),
  },
  {
    name: 'Pacific NW Estate Clearance',
    slug: 'pacific-nw-estate-clearance-seattle-wa',
    category: 'estate_cleanout',
    description: 'Full-service estate cleanout in Seattle and the Puget Sound region. We handle the hard parts for you.',
    phone: '2068907654',
    email: 'info@pacificnwestates.com',
    street_address: '1st Ave & Pike St',
    city: 'Seattle',
    state: 'WA',
    state_full: 'Washington',
    zip_code: '98101',
    years_in_business: 11,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(6, 3),
  },

  // ── Florida (Miami, Orlando, Tampa) ─────────────────────
  {
    name: 'Miami Junk Runners',
    slug: 'miami-junk-runners-fl',
    category: 'junk_removal',
    description: 'Fast and friendly junk removal in Miami-Dade. We haul away furniture, appliances, yard waste, and storm debris.',
    phone: '3055671234',
    email: 'miami@junkrunners.com',
    street_address: '1000 Brickell Ave',
    city: 'Miami',
    state: 'FL',
    state_full: 'Florida',
    zip_code: '33131',
    years_in_business: 4,
    insured: true,
    bonded: false,
    featured: false,
    images: junkPhotos(0, 3),
  },
  {
    name: 'South Florida Estate Pros',
    slug: 'south-florida-estate-pros-miami-fl',
    category: 'estate_cleanout',
    description: 'Estate cleanout experts serving Miami and Broward County. Bilingual staff available. Respectful and thorough.',
    phone: '3058907654',
    email: 'info@sfestateprops.com',
    street_address: '444 Brickell Ave',
    city: 'Miami',
    state: 'FL',
    state_full: 'Florida',
    zip_code: '33131',
    years_in_business: 8,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(1, 3),
  },
  {
    name: 'Orlando Hauling Heroes',
    slug: 'orlando-hauling-heroes-fl',
    category: 'junk_removal',
    description: 'Central Florida\'s top junk removal service. Same-day appointments available 7 days a week.',
    phone: '4075671234',
    email: 'orlando@haulingheroes.com',
    street_address: '55 W Church St',
    city: 'Orlando',
    state: 'FL',
    state_full: 'Florida',
    zip_code: '32801',
    years_in_business: 3,
    insured: true,
    bonded: false,
    featured: false,
    images: junkPhotos(2, 3),
  },
  {
    name: 'Tampa Bay Estate Cleanouts',
    slug: 'tampa-bay-estate-cleanouts-fl',
    category: 'estate_cleanout',
    description: 'Serving Tampa Bay with complete estate cleanout solutions. Families, realtors, and property managers trust us.',
    phone: '8135671234',
    email: 'tampa@tbec.com',
    street_address: '400 N Ashley Dr',
    city: 'Tampa',
    state: 'FL',
    state_full: 'Florida',
    zip_code: '33602',
    years_in_business: 6,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(3, 3),
  },

  // ── Massachusetts (Boston) ───────────────────────────────
  {
    name: 'Boston Junk Haulers',
    slug: 'boston-junk-haulers-ma',
    category: 'junk_removal',
    description: 'Greater Boston junk removal specialists. Experienced crew for narrow streets and old-home construction.',
    phone: '6175671234',
    email: 'boston@junkhaulers.com',
    street_address: '100 Cambridge St',
    city: 'Boston',
    state: 'MA',
    state_full: 'Massachusetts',
    zip_code: '02114',
    years_in_business: 9,
    insured: true,
    bonded: true,
    featured: false,
    images: junkPhotos(4, 3),
  },
  {
    name: 'New England Estate Solutions',
    slug: 'new-england-estate-solutions-boston-ma',
    category: 'estate_cleanout',
    description: 'Full estate cleanout services throughout Greater Boston and New England. Donation coordination and clean-broom service included.',
    phone: '6178907654',
    email: 'info@neestatesolutions.com',
    street_address: '200 State St',
    city: 'Boston',
    state: 'MA',
    state_full: 'Massachusetts',
    zip_code: '02109',
    years_in_business: 14,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(5, 3),
  },

  // ── Additional businesses ────────────────────────────────
  {
    name: 'Clear It Out Dallas',
    slug: 'clear-it-out-dallas-tx',
    category: 'junk_removal',
    description: 'Budget-friendly junk removal in Dallas. Transparent pricing, no hidden fees.',
    phone: '2145670001',
    email: 'info@clearitoutdallas.com',
    street_address: '2800 N Stemmons Fwy',
    city: 'Dallas',
    state: 'TX',
    state_full: 'Texas',
    zip_code: '75207',
    years_in_business: 2,
    insured: true,
    bonded: false,
    featured: false,
    images: junkPhotos(6, 2),
  },
  {
    name: 'Austin Attic Angels',
    slug: 'austin-attic-angels-tx',
    category: 'estate_cleanout',
    description: 'Specializing in attic and garage cleanouts in Austin. We sort, donate, and haul in one visit.',
    phone: '5126671234',
    email: 'info@austinaticlangels.com',
    street_address: '7000 Burnet Rd',
    city: 'Austin',
    state: 'TX',
    state_full: 'Texas',
    zip_code: '78757',
    years_in_business: 4,
    insured: true,
    bonded: false,
    featured: false,
    images: estatePhotos(7, 2),
  },
  {
    name: 'Riverside Junk Removal',
    slug: 'riverside-junk-removal-ca',
    category: 'junk_removal',
    description: 'Affordable junk removal in the Inland Empire. Mattresses, furniture, and construction debris accepted.',
    phone: '9515671234',
    email: 'info@riversidejunk.com',
    street_address: '3500 Market St',
    city: 'Riverside',
    state: 'CA',
    state_full: 'California',
    zip_code: '92501',
    years_in_business: 5,
    insured: true,
    bonded: false,
    featured: false,
    images: junkPhotos(1, 3),
  },
  {
    name: 'Sacramento Estate Clearance',
    slug: 'sacramento-estate-clearance-ca',
    category: 'estate_cleanout',
    description: 'Professional estate cleanout in Sacramento and the Central Valley. We coordinate with property managers and realtors.',
    phone: '9165671234',
    email: 'sac@estatesolutions.com',
    street_address: '1000 J St',
    city: 'Sacramento',
    state: 'CA',
    state_full: 'California',
    zip_code: '95814',
    years_in_business: 11,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(0, 3),
  },
  {
    name: 'Naperville Junk Away',
    slug: 'naperville-junk-away-il',
    category: 'junk_removal',
    description: 'Serving Naperville and Chicago suburbs. Fast, courteous, and priced right.',
    phone: '6305671234',
    email: 'info@napervillejunk.com',
    street_address: '55 S Main St',
    city: 'Naperville',
    state: 'IL',
    state_full: 'Illinois',
    zip_code: '60540',
    years_in_business: 6,
    insured: true,
    bonded: true,
    featured: false,
    images: junkPhotos(3, 3),
  },
  {
    name: 'Illinois Estate Clearers',
    slug: 'illinois-estate-clearers-naperville-il',
    category: 'estate_cleanout',
    description: 'Estate cleanout specialists for Chicago suburbs. Respectful handling of sentimental items, full-cleanout service.',
    phone: '6308901234',
    email: 'info@ileclearers.com',
    street_address: '120 Water St',
    city: 'Naperville',
    state: 'IL',
    state_full: 'Illinois',
    zip_code: '60540',
    years_in_business: 9,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(4, 3),
  },
  {
    name: 'Brooklyn Junk & Haul',
    slug: 'brooklyn-junk-and-haul-ny',
    category: 'junk_removal',
    description: 'Brooklyn-based junk removal for apartments and row houses. No elevator? No problem.',
    phone: '7185671234',
    email: 'brooklyn@junkhaul.com',
    street_address: '500 Atlantic Ave',
    city: 'Brooklyn',
    state: 'NY',
    state_full: 'New York',
    zip_code: '11217',
    years_in_business: 5,
    insured: true,
    bonded: false,
    featured: false,
    images: junkPhotos(5, 3),
  },
  {
    name: 'Queens Estate Services',
    slug: 'queens-estate-services-ny',
    category: 'estate_cleanout',
    description: 'Estate cleanout across Queens and Long Island. Multi-lingual staff, compassionate service.',
    phone: '7188901234',
    email: 'info@queensestate.com',
    street_address: '90-01 Queens Blvd',
    city: 'Queens',
    state: 'NY',
    state_full: 'New York',
    zip_code: '11373',
    years_in_business: 12,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(2, 3),
  },
  {
    name: 'Valley of the Sun Junk Co.',
    slug: 'valley-of-the-sun-junk-co-scottsdale-az',
    category: 'junk_removal',
    description: 'Scottsdale and Tempe junk removal. We handle pool removal, hot tub removal, and large item hauls.',
    phone: '4805671234',
    email: 'info@valleyofsunjunk.com',
    street_address: '7014 E Camelback Rd',
    city: 'Scottsdale',
    state: 'AZ',
    state_full: 'Arizona',
    zip_code: '85251',
    years_in_business: 7,
    insured: true,
    bonded: true,
    featured: false,
    images: junkPhotos(7, 3),
  },
  {
    name: 'Arizona Estate Pro',
    slug: 'arizona-estate-pro-scottsdale-az',
    category: 'estate_cleanout',
    description: 'Comprehensive estate cleanout for Scottsdale, Tempe, and Mesa. Respectful, efficient, and affordable.',
    phone: '4808901234',
    email: 'info@azestatepro.com',
    street_address: '3800 N Scottsdale Rd',
    city: 'Scottsdale',
    state: 'AZ',
    state_full: 'Arizona',
    zip_code: '85251',
    years_in_business: 10,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(6, 3),
  },
  {
    name: 'Marietta Junk & Debris',
    slug: 'marietta-junk-and-debris-ga',
    category: 'junk_removal',
    description: 'Cobb County and north Atlanta junk removal. Competitive rates, same-day pickups available.',
    phone: '7705671234',
    email: 'info@mariettajunk.com',
    street_address: '200 Lawrence St NE',
    city: 'Marietta',
    state: 'GA',
    state_full: 'Georgia',
    zip_code: '30060',
    years_in_business: 4,
    insured: true,
    bonded: false,
    featured: false,
    images: junkPhotos(0, 2),
  },
  {
    name: 'Georgia Estate Cleanout Network',
    slug: 'georgia-estate-cleanout-network-marietta-ga',
    category: 'estate_cleanout',
    description: 'North Atlanta estate cleanout specialists. We coordinate with realtors and family members throughout.',
    phone: '7708901234',
    email: 'info@gaecnetwork.com',
    street_address: '165 Church St NE',
    city: 'Marietta',
    state: 'GA',
    state_full: 'Georgia',
    zip_code: '30060',
    years_in_business: 7,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(1, 3),
  },
  {
    name: 'Tacoma Haul & Remove',
    slug: 'tacoma-haul-and-remove-wa',
    category: 'junk_removal',
    description: 'Pierce County and Tacoma junk removal. Affordable rates for residential and commercial customers.',
    phone: '2535671234',
    email: 'info@tacomahaul.com',
    street_address: '1102 Broadway',
    city: 'Tacoma',
    state: 'WA',
    state_full: 'Washington',
    zip_code: '98402',
    years_in_business: 5,
    insured: true,
    bonded: false,
    featured: false,
    images: junkPhotos(2, 3),
  },
  {
    name: 'Colorado Springs Cleanout Crew',
    slug: 'colorado-springs-cleanout-crew-co',
    category: 'estate_cleanout',
    description: 'Estate and property cleanout services in Colorado Springs and Pueblo. Thorough, respectful, affordable.',
    phone: '7195671234',
    email: 'info@cscleanout.com',
    street_address: '102 S Tejon St',
    city: 'Colorado Springs',
    state: 'CO',
    state_full: 'Colorado',
    zip_code: '80903',
    years_in_business: 6,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(7, 3),
  },
  {
    name: 'Fort Lauderdale Junk Experts',
    slug: 'fort-lauderdale-junk-experts-fl',
    category: 'junk_removal',
    description: 'Broward County\'s junk removal experts. Boats, trailers, appliances, and full-home cleanouts.',
    phone: '9545671234',
    email: 'info@ftlaudjunk.com',
    street_address: '100 Andrews Ave',
    city: 'Fort Lauderdale',
    state: 'FL',
    state_full: 'Florida',
    zip_code: '33301',
    years_in_business: 8,
    insured: true,
    bonded: true,
    featured: false,
    images: junkPhotos(4, 3),
  },
  {
    name: 'Cambridge Estate Clearers',
    slug: 'cambridge-estate-clearers-ma',
    category: 'estate_cleanout',
    description: 'Estate cleanout serving Cambridge, Somerville, and Greater Boston. Discreet and efficient service.',
    phone: '6174567890',
    email: 'info@cambridgeec.com',
    street_address: '1000 Massachusetts Ave',
    city: 'Cambridge',
    state: 'MA',
    state_full: 'Massachusetts',
    zip_code: '02138',
    years_in_business: 15,
    insured: true,
    bonded: true,
    featured: false,
    images: estatePhotos(3, 3),
  },
]

// ════════════════════════════════════════════════════════════
// Seed Reviews (~4–6 per business for representative sample)
// ════════════════════════════════════════════════════════════
const reviewBodies = {
  positive: [
    'The crew arrived on time and worked incredibly fast. My garage looks like a completely different space. Highly recommend!',
    'Excellent service from start to finish. They were professional, courteous, and took care of everything in one trip.',
    'Pricing was transparent and fair. No hidden fees, no surprises. Will definitely use again.',
    'I was amazed by how quickly they cleared everything out. The team was respectful of our home and left no mess behind.',
    'Outstanding work. They even swept up after themselves. Truly above and beyond.',
    'Very professional outfit. They arrived on time, worked efficiently, and the price matched the quote exactly.',
  ],
  neutral: [
    'Good service overall. Would have appreciated a bit more communication on arrival time but the work was solid.',
    'Decent experience. The team was friendly and got the job done. Took a little longer than expected.',
    'Fair pricing and good work. A small item was left behind but they came back promptly to retrieve it.',
    'Solid service. Nothing extraordinary but they got the job done without issues.',
  ],
  negative: [
    'Service was okay but the team was a bit rough with a few items I wanted donated. Communication could be better.',
    'Had to follow up twice to confirm the appointment. The work itself was fine once they arrived.',
  ],
}

export const SEED_REVIEWS: SeedReview[] = [
  // Lone Star Junk Austin
  { business_slug: 'lone-star-junk-austin-tx', reviewer_name: 'Maria G.', rating: 5, title: 'Best junk removal in Austin!', body: reviewBodies.positive[0] },
  { business_slug: 'lone-star-junk-austin-tx', reviewer_name: 'Derek T.', rating: 5, title: 'Incredibly fast and professional', body: reviewBodies.positive[1] },
  { business_slug: 'lone-star-junk-austin-tx', reviewer_name: 'Sarah K.', rating: 4, title: 'Great experience', body: reviewBodies.neutral[0] },
  { business_slug: 'lone-star-junk-austin-tx', reviewer_name: 'Tom P.', rating: 5, title: 'Will use again!', body: reviewBodies.positive[2] },

  // Capital City Estate Cleanouts
  { business_slug: 'capital-city-estate-cleanouts-austin-tx', reviewer_name: 'Lisa M.', rating: 5, title: 'Handled mom\'s estate perfectly', body: reviewBodies.positive[3] },
  { business_slug: 'capital-city-estate-cleanouts-austin-tx', reviewer_name: 'Carlos R.', rating: 5, title: 'Compassionate and thorough', body: reviewBodies.positive[4] },
  { business_slug: 'capital-city-estate-cleanouts-austin-tx', reviewer_name: 'Janet F.', rating: 4, title: 'Very good service', body: reviewBodies.neutral[1] },
  { business_slug: 'capital-city-estate-cleanouts-austin-tx', reviewer_name: 'Bob W.', rating: 5, title: 'Highly recommend', body: reviewBodies.positive[5] },

  // H-Town Haul Away
  { business_slug: 'h-town-haul-away-houston-tx', reviewer_name: 'James L.', rating: 4, title: 'Good Houston service', body: reviewBodies.positive[0] },
  { business_slug: 'h-town-haul-away-houston-tx', reviewer_name: 'Amy C.', rating: 5, title: 'Super quick pickup', body: reviewBodies.positive[1] },
  { business_slug: 'h-town-haul-away-houston-tx', reviewer_name: 'Paul N.', rating: 3, title: 'Decent but late', body: reviewBodies.neutral[0] },
  { business_slug: 'h-town-haul-away-houston-tx', reviewer_name: 'Kim S.', rating: 4, title: 'Would use again', body: reviewBodies.neutral[3] },

  // Houston Estate Clearance Pro
  { business_slug: 'houston-estate-clearance-pro-tx', reviewer_name: 'Grace T.', rating: 5, title: 'Handled everything with care', body: reviewBodies.positive[3] },
  { business_slug: 'houston-estate-clearance-pro-tx', reviewer_name: 'Mark D.', rating: 5, title: 'Excellent professional team', body: reviewBodies.positive[5] },
  { business_slug: 'houston-estate-clearance-pro-tx', reviewer_name: 'Pam H.', rating: 4, title: 'Good experience overall', body: reviewBodies.neutral[2] },

  // DFW Junk Masters
  { business_slug: 'dfw-junk-masters-dallas-tx', reviewer_name: 'Tyler B.', rating: 5, title: 'Top-notch DFW service', body: reviewBodies.positive[0] },
  { business_slug: 'dfw-junk-masters-dallas-tx', reviewer_name: 'Sandra E.', rating: 5, title: 'Fast and clean', body: reviewBodies.positive[4] },
  { business_slug: 'dfw-junk-masters-dallas-tx', reviewer_name: 'Mike A.', rating: 5, title: 'Best in Dallas', body: reviewBodies.positive[1] },
  { business_slug: 'dfw-junk-masters-dallas-tx', reviewer_name: 'Rachel C.', rating: 4, title: 'Great job overall', body: reviewBodies.neutral[1] },

  // Texas Estates Cleanout
  { business_slug: 'texas-estates-cleanout-dallas-tx', reviewer_name: 'Linda J.', rating: 5, title: 'Cleared my dad\'s house perfectly', body: reviewBodies.positive[3] },
  { business_slug: 'texas-estates-cleanout-dallas-tx', reviewer_name: 'David K.', rating: 5, title: 'Professional and kind', body: reviewBodies.positive[2] },
  { business_slug: 'texas-estates-cleanout-dallas-tx', reviewer_name: 'Susan M.', rating: 4, title: 'Really helpful team', body: reviewBodies.neutral[0] },

  // LA Junk Busters
  { business_slug: 'la-junk-busters-los-angeles-ca', reviewer_name: 'Chris P.', rating: 5, title: 'LA\'s best junk service', body: reviewBodies.positive[0] },
  { business_slug: 'la-junk-busters-los-angeles-ca', reviewer_name: 'Megan V.', rating: 5, title: 'Quick and affordable', body: reviewBodies.positive[2] },
  { business_slug: 'la-junk-busters-los-angeles-ca', reviewer_name: 'Kevin L.', rating: 5, title: 'Amazing crew', body: reviewBodies.positive[4] },
  { business_slug: 'la-junk-busters-los-angeles-ca', reviewer_name: 'Diana R.', rating: 3, title: 'Good but small hiccup', body: reviewBodies.negative[0] },

  // Hollywood Estate Solutions
  { business_slug: 'hollywood-estate-solutions-ca', reviewer_name: 'Nicole F.', rating: 5, title: 'Discreet and professional', body: reviewBodies.positive[5] },
  { business_slug: 'hollywood-estate-solutions-ca', reviewer_name: 'Brian K.', rating: 4, title: 'Good experience', body: reviewBodies.neutral[3] },
  { business_slug: 'hollywood-estate-solutions-ca', reviewer_name: 'Jessica T.', rating: 5, title: 'Made a hard time easier', body: reviewBodies.positive[3] },

  // Bay Area Junk Away
  { business_slug: 'bay-area-junk-away-san-francisco-ca', reviewer_name: 'Alex M.', rating: 5, title: 'Eco-friendly and fast', body: reviewBodies.positive[1] },
  { business_slug: 'bay-area-junk-away-san-francisco-ca', reviewer_name: 'Priya N.', rating: 5, title: 'Great SF service', body: reviewBodies.positive[0] },
  { business_slug: 'bay-area-junk-away-san-francisco-ca', reviewer_name: 'Ryan G.', rating: 4, title: 'Solid eco service', body: reviewBodies.neutral[2] },

  // Golden Gate Estate Cleaners
  { business_slug: 'golden-gate-estate-cleaners-sf-ca', reviewer_name: 'Helen W.', rating: 5, title: 'Superb estate service', body: reviewBodies.positive[4] },
  { business_slug: 'golden-gate-estate-cleaners-sf-ca', reviewer_name: 'Frank O.', rating: 4, title: 'Good and thorough', body: reviewBodies.neutral[0] },
  { business_slug: 'golden-gate-estate-cleaners-sf-ca', reviewer_name: 'Tina L.', rating: 5, title: 'Would recommend to anyone', body: reviewBodies.positive[5] },

  // San Diego Clutter Crushers
  { business_slug: 'san-diego-clutter-crushers-ca', reviewer_name: 'Matt R.', rating: 4, title: 'Great SD service', body: reviewBodies.positive[2] },
  { business_slug: 'san-diego-clutter-crushers-ca', reviewer_name: 'Caitlin B.', rating: 3, title: 'Okay experience', body: reviewBodies.neutral[1] },
  { business_slug: 'san-diego-clutter-crushers-ca', reviewer_name: 'Drew S.', rating: 4, title: 'Fast and clean', body: reviewBodies.neutral[3] },

  // Windy City Junk Removal
  { business_slug: 'windy-city-junk-removal-chicago-il', reviewer_name: 'Pat B.', rating: 5, title: 'Best in Chicago!', body: reviewBodies.positive[0] },
  { business_slug: 'windy-city-junk-removal-chicago-il', reviewer_name: 'Diane L.', rating: 5, title: 'Year-round reliable service', body: reviewBodies.positive[1] },
  { business_slug: 'windy-city-junk-removal-chicago-il', reviewer_name: 'Tony M.', rating: 5, title: 'Great crew', body: reviewBodies.positive[4] },
  { business_slug: 'windy-city-junk-removal-chicago-il', reviewer_name: 'Rosa C.', rating: 4, title: 'Would use again', body: reviewBodies.neutral[2] },

  // Chicago Estate Cleanout Co.
  { business_slug: 'chicago-estate-cleanout-co-il', reviewer_name: 'Angie W.', rating: 5, title: 'Handled a tough situation', body: reviewBodies.positive[3] },
  { business_slug: 'chicago-estate-cleanout-co-il', reviewer_name: 'Ben H.', rating: 5, title: 'Professional and compassionate', body: reviewBodies.positive[5] },
  { business_slug: 'chicago-estate-cleanout-co-il', reviewer_name: 'Nancy D.', rating: 4, title: 'Good service', body: reviewBodies.neutral[0] },

  // Loop Junk Haulers
  { business_slug: 'loop-junk-haulers-chicago-il', reviewer_name: 'Jose R.', rating: 4, title: 'Great condo service', body: reviewBodies.positive[2] },
  { business_slug: 'loop-junk-haulers-chicago-il', reviewer_name: 'Karen T.', rating: 3, title: 'Decent but slow', body: reviewBodies.neutral[1] },
  { business_slug: 'loop-junk-haulers-chicago-il', reviewer_name: 'Sam F.', rating: 4, title: 'Got the job done', body: reviewBodies.neutral[3] },

  // NYC Junk Removal Pros
  { business_slug: 'nyc-junk-removal-pros-new-york-ny', reviewer_name: 'Vera K.', rating: 5, title: 'NYC approved!', body: reviewBodies.positive[0] },
  { business_slug: 'nyc-junk-removal-pros-new-york-ny', reviewer_name: 'Omar J.', rating: 4, title: 'Navigated our building perfectly', body: reviewBodies.neutral[0] },
  { business_slug: 'nyc-junk-removal-pros-new-york-ny', reviewer_name: 'Faye M.', rating: 5, title: 'Fast and efficient', body: reviewBodies.positive[4] },

  // Manhattan Estate Clearance
  { business_slug: 'manhattan-estate-clearance-ny', reviewer_name: 'Richard A.', rating: 5, title: 'White-glove service truly delivered', body: reviewBodies.positive[5] },
  { business_slug: 'manhattan-estate-clearance-ny', reviewer_name: 'Barbara N.', rating: 5, title: 'Exceptional estate service', body: reviewBodies.positive[3] },
  { business_slug: 'manhattan-estate-clearance-ny', reviewer_name: 'George P.', rating: 4, title: 'Very professional', body: reviewBodies.neutral[2] },

  // Empire State Junk Haulers
  { business_slug: 'empire-state-junk-haulers-buffalo-ny', reviewer_name: 'Linda C.', rating: 4, title: 'Good Buffalo service', body: reviewBodies.positive[2] },
  { business_slug: 'empire-state-junk-haulers-buffalo-ny', reviewer_name: 'Bill H.', rating: 3, title: 'Average experience', body: reviewBodies.neutral[1] },
  { business_slug: 'empire-state-junk-haulers-buffalo-ny', reviewer_name: 'Wendy M.', rating: 4, title: 'Would recommend', body: reviewBodies.neutral[3] },

  // Desert Sun Junk Removal
  { business_slug: 'desert-sun-junk-removal-phoenix-az', reviewer_name: 'Hector L.', rating: 5, title: 'Great Phoenix service', body: reviewBodies.positive[1] },
  { business_slug: 'desert-sun-junk-removal-phoenix-az', reviewer_name: 'Cindy R.', rating: 4, title: 'Fast and reliable', body: reviewBodies.neutral[0] },
  { business_slug: 'desert-sun-junk-removal-phoenix-az', reviewer_name: 'Aaron T.', rating: 5, title: 'Cleared my yard in 2 hours', body: reviewBodies.positive[0] },

  // Sonoran Estate Cleanouts
  { business_slug: 'sonoran-estate-cleanouts-phoenix-az', reviewer_name: 'Martha G.', rating: 5, title: 'Kind and thorough', body: reviewBodies.positive[3] },
  { business_slug: 'sonoran-estate-cleanouts-phoenix-az', reviewer_name: 'Roy B.', rating: 4, title: 'Good estate service', body: reviewBodies.neutral[2] },
  { business_slug: 'sonoran-estate-cleanouts-phoenix-az', reviewer_name: 'Iris F.', rating: 5, title: 'Highly recommend', body: reviewBodies.positive[5] },

  // Tucson Tough Haulers
  { business_slug: 'tucson-tough-haulers-az', reviewer_name: 'Chad N.', rating: 4, title: 'Good Tucson service', body: reviewBodies.neutral[3] },
  { business_slug: 'tucson-tough-haulers-az', reviewer_name: 'Emily V.', rating: 4, title: 'Competitive price', body: reviewBodies.positive[2] },
  { business_slug: 'tucson-tough-haulers-az', reviewer_name: 'Nick P.', rating: 3, title: 'Decent overall', body: reviewBodies.negative[1] },

  // ATL Junk Removal Squad
  { business_slug: 'atl-junk-removal-squad-atlanta-ga', reviewer_name: 'Keisha W.', rating: 5, title: 'Amazing ATL team', body: reviewBodies.positive[4] },
  { business_slug: 'atl-junk-removal-squad-atlanta-ga', reviewer_name: 'Marcus T.', rating: 5, title: 'Fast and green', body: reviewBodies.positive[1] },
  { business_slug: 'atl-junk-removal-squad-atlanta-ga', reviewer_name: 'Angela P.', rating: 4, title: 'Great experience', body: reviewBodies.neutral[0] },

  // Peach State Estate Cleaners
  { business_slug: 'peach-state-estate-cleaners-atlanta-ga', reviewer_name: 'Carla J.', rating: 5, title: 'Handled grandmother\'s estate', body: reviewBodies.positive[3] },
  { business_slug: 'peach-state-estate-cleaners-atlanta-ga', reviewer_name: 'Deon R.', rating: 5, title: 'Excellent team', body: reviewBodies.positive[5] },
  { business_slug: 'peach-state-estate-cleaners-atlanta-ga', reviewer_name: 'Tonya K.', rating: 4, title: 'Professional service', body: reviewBodies.neutral[1] },

  // Mile High Junk Removal
  { business_slug: 'mile-high-junk-removal-denver-co', reviewer_name: 'Jake L.', rating: 5, title: 'Denver\'s finest!', body: reviewBodies.positive[0] },
  { business_slug: 'mile-high-junk-removal-denver-co', reviewer_name: 'Brooke H.', rating: 5, title: 'Super eco-friendly', body: reviewBodies.positive[4] },
  { business_slug: 'mile-high-junk-removal-denver-co', reviewer_name: 'Cole M.', rating: 4, title: 'Good mountain city service', body: reviewBodies.neutral[2] },

  // Rocky Mountain Estate Services
  { business_slug: 'rocky-mountain-estate-services-denver-co', reviewer_name: 'Patricia E.', rating: 5, title: 'Excellent and thorough', body: reviewBodies.positive[5] },
  { business_slug: 'rocky-mountain-estate-services-denver-co', reviewer_name: 'Steven R.', rating: 4, title: 'Very professional', body: reviewBodies.neutral[0] },
  { business_slug: 'rocky-mountain-estate-services-denver-co', reviewer_name: 'Amanda T.', rating: 5, title: 'Helped us through a tough time', body: reviewBodies.positive[3] },

  // Emerald City Junk Removal
  { business_slug: 'emerald-city-junk-removal-seattle-wa', reviewer_name: 'Travis O.', rating: 5, title: 'Seattle loves them', body: reviewBodies.positive[1] },
  { business_slug: 'emerald-city-junk-removal-seattle-wa', reviewer_name: 'Amber K.', rating: 4, title: 'Great sustainable service', body: reviewBodies.neutral[3] },
  { business_slug: 'emerald-city-junk-removal-seattle-wa', reviewer_name: 'Logan S.', rating: 5, title: 'Fast and green removal', body: reviewBodies.positive[2] },

  // Pacific NW Estate Clearance
  { business_slug: 'pacific-nw-estate-clearance-seattle-wa', reviewer_name: 'Natalie B.', rating: 5, title: 'They handled everything', body: reviewBodies.positive[4] },
  { business_slug: 'pacific-nw-estate-clearance-seattle-wa', reviewer_name: 'Oliver P.', rating: 5, title: 'Remarkable team', body: reviewBodies.positive[5] },
  { business_slug: 'pacific-nw-estate-clearance-seattle-wa', reviewer_name: 'Hannah M.', rating: 4, title: 'Solid PNW service', body: reviewBodies.neutral[1] },

  // Miami Junk Runners
  { business_slug: 'miami-junk-runners-fl', reviewer_name: 'Daniela C.', rating: 5, title: 'Quick Miami pickup', body: reviewBodies.positive[0] },
  { business_slug: 'miami-junk-runners-fl', reviewer_name: 'Carlos M.', rating: 4, title: 'Great value', body: reviewBodies.neutral[2] },
  { business_slug: 'miami-junk-runners-fl', reviewer_name: 'Sofia A.', rating: 4, title: 'Friendly team', body: reviewBodies.positive[2] },

  // South Florida Estate Pros
  { business_slug: 'south-florida-estate-pros-miami-fl', reviewer_name: 'Roberto V.', rating: 5, title: 'Bilingual and professional', body: reviewBodies.positive[3] },
  { business_slug: 'south-florida-estate-pros-miami-fl', reviewer_name: 'Isabel G.', rating: 5, title: 'Amazing service', body: reviewBodies.positive[5] },
  { business_slug: 'south-florida-estate-pros-miami-fl', reviewer_name: 'Miguel R.', rating: 4, title: 'Would recommend', body: reviewBodies.neutral[0] },

  // Orlando Hauling Heroes
  { business_slug: 'orlando-hauling-heroes-fl', reviewer_name: 'Jake T.', rating: 4, title: 'Fast Orlando service', body: reviewBodies.neutral[3] },
  { business_slug: 'orlando-hauling-heroes-fl', reviewer_name: 'Lisa B.', rating: 5, title: 'Super fast same day!', body: reviewBodies.positive[1] },
  { business_slug: 'orlando-hauling-heroes-fl', reviewer_name: 'Dan K.', rating: 3, title: 'OK experience', body: reviewBodies.neutral[1] },

  // Tampa Bay Estate Cleanouts
  { business_slug: 'tampa-bay-estate-cleanouts-fl', reviewer_name: 'Gina P.', rating: 5, title: 'Perfect Tampa service', body: reviewBodies.positive[4] },
  { business_slug: 'tampa-bay-estate-cleanouts-fl', reviewer_name: 'Fred L.', rating: 4, title: 'Reliable and professional', body: reviewBodies.neutral[2] },
  { business_slug: 'tampa-bay-estate-cleanouts-fl', reviewer_name: 'Helen S.', rating: 5, title: 'Best in Tampa Bay', body: reviewBodies.positive[0] },

  // Boston Junk Haulers
  { business_slug: 'boston-junk-haulers-ma', reviewer_name: 'Sean O.', rating: 5, title: 'Great Boston team', body: reviewBodies.positive[1] },
  { business_slug: 'boston-junk-haulers-ma', reviewer_name: 'Bridget F.', rating: 4, title: 'Handled narrow streets fine', body: reviewBodies.neutral[0] },
  { business_slug: 'boston-junk-haulers-ma', reviewer_name: 'Patrick M.', rating: 5, title: 'Outstanding work', body: reviewBodies.positive[5] },

  // New England Estate Solutions
  { business_slug: 'new-england-estate-solutions-boston-ma', reviewer_name: 'Dorothy K.', rating: 5, title: 'Compassionate Boston service', body: reviewBodies.positive[3] },
  { business_slug: 'new-england-estate-solutions-boston-ma', reviewer_name: 'Walter H.', rating: 5, title: 'Excellent estate clearance', body: reviewBodies.positive[4] },
  { business_slug: 'new-england-estate-solutions-boston-ma', reviewer_name: 'Florence T.', rating: 4, title: 'Good experience', body: reviewBodies.neutral[3] },

  // Additional businesses (2-3 reviews each)
  { business_slug: 'clear-it-out-dallas-tx', reviewer_name: 'Neil B.', rating: 4, title: 'Budget-friendly and good', body: reviewBodies.positive[2] },
  { business_slug: 'clear-it-out-dallas-tx', reviewer_name: 'Tara M.', rating: 4, title: 'No hidden fees — refreshing!', body: reviewBodies.neutral[2] },

  { business_slug: 'austin-attic-angels-tx', reviewer_name: 'Christine P.', rating: 5, title: 'Attic gone in 3 hours!', body: reviewBodies.positive[0] },
  { business_slug: 'austin-attic-angels-tx', reviewer_name: 'Jason R.', rating: 4, title: 'Sorted and hauled everything', body: reviewBodies.neutral[1] },

  { business_slug: 'riverside-junk-removal-ca', reviewer_name: 'Victor S.', rating: 4, title: 'Good IE service', body: reviewBodies.positive[2] },
  { business_slug: 'riverside-junk-removal-ca', reviewer_name: 'Crystal B.', rating: 3, title: 'Average experience', body: reviewBodies.neutral[1] },

  { business_slug: 'sacramento-estate-clearance-ca', reviewer_name: 'Donna H.', rating: 5, title: 'Great Sacramento team', body: reviewBodies.positive[3] },
  { business_slug: 'sacramento-estate-clearance-ca', reviewer_name: 'Roger T.', rating: 4, title: 'Professional service', body: reviewBodies.neutral[0] },

  { business_slug: 'naperville-junk-away-il', reviewer_name: 'Heidi M.', rating: 5, title: 'Best Naperville option', body: reviewBodies.positive[1] },
  { business_slug: 'naperville-junk-away-il', reviewer_name: 'Bruce F.', rating: 4, title: 'Good suburban service', body: reviewBodies.neutral[3] },

  { business_slug: 'illinois-estate-clearers-naperville-il', reviewer_name: 'Louise A.', rating: 5, title: 'Respectful and efficient', body: reviewBodies.positive[5] },
  { business_slug: 'illinois-estate-clearers-naperville-il', reviewer_name: 'Dean K.', rating: 4, title: 'Good cleanout service', body: reviewBodies.neutral[2] },

  { business_slug: 'brooklyn-junk-and-haul-ny', reviewer_name: 'Yolanda M.', rating: 4, title: 'Great Brooklyn service', body: reviewBodies.positive[0] },
  { business_slug: 'brooklyn-junk-and-haul-ny', reviewer_name: 'Adrian L.', rating: 5, title: 'Handled our walkup perfectly', body: reviewBodies.positive[4] },

  { business_slug: 'queens-estate-services-ny', reviewer_name: 'Fatima O.', rating: 5, title: 'Multilingual and professional', body: reviewBodies.positive[3] },
  { business_slug: 'queens-estate-services-ny', reviewer_name: 'Kwame J.', rating: 4, title: 'Good Queens service', body: reviewBodies.neutral[0] },

  { business_slug: 'valley-of-the-sun-junk-co-scottsdale-az', reviewer_name: 'Brittany N.', rating: 5, title: 'Hot tub removed no problem', body: reviewBodies.positive[1] },
  { business_slug: 'valley-of-the-sun-junk-co-scottsdale-az', reviewer_name: 'Lance H.', rating: 4, title: 'Fast Scottsdale service', body: reviewBodies.neutral[2] },

  { business_slug: 'arizona-estate-pro-scottsdale-az', reviewer_name: 'Debra F.', rating: 5, title: 'Excellent Scottsdale estate service', body: reviewBodies.positive[5] },
  { business_slug: 'arizona-estate-pro-scottsdale-az', reviewer_name: 'Timothy R.', rating: 4, title: 'Would use again', body: reviewBodies.neutral[1] },

  { business_slug: 'marietta-junk-and-debris-ga', reviewer_name: 'Gwen A.', rating: 4, title: 'Competitive Marietta pricing', body: reviewBodies.positive[2] },
  { business_slug: 'marietta-junk-and-debris-ga', reviewer_name: 'Kirk L.', rating: 3, title: 'Decent service', body: reviewBodies.negative[1] },

  { business_slug: 'georgia-estate-cleanout-network-marietta-ga', reviewer_name: 'Lori D.', rating: 5, title: 'Coordinated perfectly with realtor', body: reviewBodies.positive[4] },
  { business_slug: 'georgia-estate-cleanout-network-marietta-ga', reviewer_name: 'Eugene P.', rating: 4, title: 'Thorough and on time', body: reviewBodies.neutral[3] },

  { business_slug: 'tacoma-haul-and-remove-wa', reviewer_name: 'Alicia T.', rating: 4, title: 'Good Tacoma service', body: reviewBodies.neutral[0] },
  { business_slug: 'tacoma-haul-and-remove-wa', reviewer_name: 'Bob N.', rating: 4, title: 'Affordable and efficient', body: reviewBodies.positive[2] },

  { business_slug: 'colorado-springs-cleanout-crew-co', reviewer_name: 'Vanessa G.', rating: 5, title: 'Great Colorado Springs team', body: reviewBodies.positive[3] },
  { business_slug: 'colorado-springs-cleanout-crew-co', reviewer_name: 'Jerome W.', rating: 4, title: 'Thorough service', body: reviewBodies.neutral[2] },

  { business_slug: 'fort-lauderdale-junk-experts-fl', reviewer_name: 'Marlene B.', rating: 5, title: 'Hauled our boat parts away!', body: reviewBodies.positive[0] },
  { business_slug: 'fort-lauderdale-junk-experts-fl', reviewer_name: 'Phil K.', rating: 4, title: 'Great Fort Lauderdale service', body: reviewBodies.neutral[1] },

  { business_slug: 'cambridge-estate-clearers-ma', reviewer_name: 'Rosalind T.', rating: 5, title: 'Academic estate handled expertly', body: reviewBodies.positive[5] },
  { business_slug: 'cambridge-estate-clearers-ma', reviewer_name: 'Henry V.', rating: 5, title: 'Discreet and efficient', body: reviewBodies.positive[1] },
  { business_slug: 'cambridge-estate-clearers-ma', reviewer_name: 'Constance M.', rating: 4, title: 'Would recommend', body: reviewBodies.neutral[3] },
]
